# Generated by Django 4.2.13 on 2024-07-12 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iterio_app', '0031_booking'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatmessage',
            options={'ordering': ['-date'], 'verbose_name_plural': 'Chat Messages'},
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='user',
        ),
    ]
